package models

import (
	"encoding/json"
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestRequest(t *testing.T) {
	assert := assert.New(t)
	body := "{ \"email\": \"abc@bc.com\"}"

	request := RequestParameter{}
	err := json.Unmarshal([]byte(body), &request)

	assert.NoError(err)
	assert.Equal(*request.Email, "abc@bc.com")
}

func TestSessionRequest(t *testing.T) {
	assert := assert.New(t)
	body := "{ \"email\": \"abc@bc.com\", \"session\": \"AYABeGiqa6VfNkELuaAvQZAeHj0AHQABAAdTZXJ2aWNlABBDb2duaXRvVXNlclBvb2xzAAEAB2F3cy1rbXMAS2Fybjphd3M6a21zOmV1LXdlc3QtMTo0NTU0NTg0OTMwODE6a2V5L2FiN2U3M2UzLWU2NDEtNDk5Zi1iNzc0LWZkZmM1MWM3NzFhYQC4AQIBAHigzwqzlp0D8sA0ltw8SHdsZPaJakxa-4NzPukgGo7dmgEyslRwbWM3GYgotkcj6jDrAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMvQB6pRV2V-NfFxTzAgEQgDvIxEmtCEhav9K9GtgDcVRFJuzkljYh7Qz4j6MYS25xba1KH-pWWYkvJZO68XMM-M5hOes1fhYtEGhgiwIAAAAADAAAEAAAAAAAAAAAAAAAAADH7xYmqgxrp0UFQEU-47W______wAAAAEAAAAAAAAAAAAAAAEAAAIAqjKxEMDVHCdDQyrIc8NtrLIQRmYUl6_UegkK3TMXIQoBJcZPREmxMhge1EP27OE1roxAN7nOF6A3Tv_ZZn-Ljd4tnbEn7lI0-v8IGsOVzSmT2ebupXmkQAJ6cDHrkO_XM6e3suqWY0I-hhOugLFxMZPThsy7vzXAHzgd-ejWL9gKVj5YV2J1GtUPTnHJoxsEl-oRRCQ6RDf0wcWMyMNngItxHh9hdb9iG0opj0ULX1SEEc1RL5zPIeWaEgCMoZ56dpKtM1NQAgaqpUY4UeTkIM96TrQxigIYihOskdjbuKE1IX66PByLk5Vdf2uWsriB_lWCkINlJzNbCn3WNCBgFY7nC3ghRgcSzX5L904iUz6pKgCO-xcEf0mbSVHLwIQMVNlIZt4wIAKBxxBJUgIEfUAsCa36h-SHfVwfBvATVkBMlQW0pSg2siFCRCRcuvbWhGPx--a4YV6_EL-YJuI0zKrFZJ3ilXgV9mnXB4RnWln-uhbpx6TUuA_ZKZSGAT9IQFclYEGFv-gd-q94VAV68zDOqOplzcfBDvHm0xuXBoJDiffzve0PJ4YAPAst9ZHV6JvwHTfmgp_VGckHPhtS0WEMLvqbIUoNV4miky7hmQmkujzSf0GzQ9_iecGGQFu5SYVwz_pRn29yv1KsacTepgEFYconZj1iQYIaE0gGcNuFol4RngiEgRDxvUsSIJq8\"}"

	request := RequestParameter{}
	err := json.Unmarshal([]byte(body), &request)

	assert.NoError(err)
	assert.Equal(*request.Email, "abc@bc.com")
	assert.Equal(*request.Session, "AYABeGiqa6VfNkELuaAvQZAeHj0AHQABAAdTZXJ2aWNlABBDb2duaXRvVXNlclBvb2xzAAEAB2F3cy1rbXMAS2Fybjphd3M6a21zOmV1LXdlc3QtMTo0NTU0NTg0OTMwODE6a2V5L2FiN2U3M2UzLWU2NDEtNDk5Zi1iNzc0LWZkZmM1MWM3NzFhYQC4AQIBAHigzwqzlp0D8sA0ltw8SHdsZPaJakxa-4NzPukgGo7dmgEyslRwbWM3GYgotkcj6jDrAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMvQB6pRV2V-NfFxTzAgEQgDvIxEmtCEhav9K9GtgDcVRFJuzkljYh7Qz4j6MYS25xba1KH-pWWYkvJZO68XMM-M5hOes1fhYtEGhgiwIAAAAADAAAEAAAAAAAAAAAAAAAAADH7xYmqgxrp0UFQEU-47W______wAAAAEAAAAAAAAAAAAAAAEAAAIAqjKxEMDVHCdDQyrIc8NtrLIQRmYUl6_UegkK3TMXIQoBJcZPREmxMhge1EP27OE1roxAN7nOF6A3Tv_ZZn-Ljd4tnbEn7lI0-v8IGsOVzSmT2ebupXmkQAJ6cDHrkO_XM6e3suqWY0I-hhOugLFxMZPThsy7vzXAHzgd-ejWL9gKVj5YV2J1GtUPTnHJoxsEl-oRRCQ6RDf0wcWMyMNngItxHh9hdb9iG0opj0ULX1SEEc1RL5zPIeWaEgCMoZ56dpKtM1NQAgaqpUY4UeTkIM96TrQxigIYihOskdjbuKE1IX66PByLk5Vdf2uWsriB_lWCkINlJzNbCn3WNCBgFY7nC3ghRgcSzX5L904iUz6pKgCO-xcEf0mbSVHLwIQMVNlIZt4wIAKBxxBJUgIEfUAsCa36h-SHfVwfBvATVkBMlQW0pSg2siFCRCRcuvbWhGPx--a4YV6_EL-YJuI0zKrFZJ3ilXgV9mnXB4RnWln-uhbpx6TUuA_ZKZSGAT9IQFclYEGFv-gd-q94VAV68zDOqOplzcfBDvHm0xuXBoJDiffzve0PJ4YAPAst9ZHV6JvwHTfmgp_VGckHPhtS0WEMLvqbIUoNV4miky7hmQmkujzSf0GzQ9_iecGGQFu5SYVwz_pRn29yv1KsacTepgEFYconZj1iQYIaE0gGcNuFol4RngiEgRDxvUsSIJq8")
}
