name: Production - Deploy ResendConfirmationCode

on:
  push:
    branches: [main]
  workflow_dispatch:
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      # Deploy ResendConfirmationCode
      - name: Deploy resend-confirmation-code
        run: cd resend-confirmation-code/; GOOS=linux CGO_ENABLED=0 go build cmd/main.go; zip addResendConfirmationCode.zip main; ls;

      - name: Deploy ResendConfirmationCode Test
        run: cd resend-confirmation-code/; go test -v ./...

      - name: Deploy ResendConfirmationCode gobuild deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: resendConfirmationCode
          zip_file: resend-confirmation-code/addResendConfirmationCode.zip
