name: Production - Deploy ConfirmSignup

on:
  push:
    branches: [main]
  workflow_dispatch:
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      # Deploy ConfirmSignup
      - name: Deploy confirm-signup
        run: cd confirm-signup/; GOOS=linux CGO_ENABLED=0 go build cmd/main.go; zip addConfirmSignup.zip main; ls;

      - name: Deploy ConfirmSignup Test
        run: cd confirm-signup/; go test -v ./...

      - name: Deploy ConfirmSignup gobuild deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: confirmSignup
          zip_file: confirm-signup/addConfirmSignup.zip
