name: Production - Deploy GlobalSignout

on:
  push:
    branches: [main]
  workflow_dispatch:
    

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      # Deploy GlobalSignout
      - name: Deploy global-signout
        run: cd global-signout/; GOOS=linux CGO_ENABLED=0 go build cmd/main.go; zip addGlobalSignout.zip main; ls;

      - name: Deploy GlobalSignout Test
        run: cd global-signout/; go test -v ./...
            
      - name: Global Signout gobuild deploy
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.OIDC_GITHUB_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: SessionRetrieveAndValidateAPIKey

      - name: Update lambda
        run: aws lambda update-function-code --function-name  globalSignout --zip-file fileb://global-signout/addGlobalSignout.zip
