name: Production - Deploy ResendConfirmationCode

on:
  push:
    branches: [main]
  workflow_dispatch:
    

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      # Deploy ResendConfirmationCode
      - name: Deploy resend-confirmation-code
        run: cd resend-confirmation-code/; GOOS=linux CGO_ENABLED=0 go build cmd/main.go; zip addResendConfirmationCode.zip main; ls;

      - name: Deploy ResendConfirmationCode Test
        run: cd resend-confirmation-code/; go test -v ./...
       
      - name: ResendConfirmationCode gobuild deploy
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.OIDC_GITHUB_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: SessionRetrieveAndValidateAPIKey

      - name: Update lambda
        run: aws lambda update-function-code --function-name  resendConfirmationCode --zip-file fileb://resend-confirmation-code/addResendConfirmationCode.zip
