name: Production - Deploy GlobalSignout

on:
  push:
    branches: [main]
  workflow_dispatch:
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      # Deploy GlobalSignout
      - name: Deploy global-signout
        run: cd global-signout/; GOOS=linux CGO_ENABLED=0 go build cmd/main.go; zip addGlobalSignout.zip main; ls;

      - name: Deploy GlobalSignout Test
        run: cd global-signout/; go test -v ./...

      - name: Deploy GlobalSignout gobuild deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: globalSignout
          zip_file: global-signout/addGlobalSignout.zip
