name: Production - Deploy ForgotPassword

on:
  push:
    branches: [main]
  workflow_dispatch:
    

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      # Deploy ForgotPassword
      - name: Deploy forgot-password
        run: cd forgot-password/; GOOS=linux CGO_ENABLED=0 go build cmd/main.go; zip addForgotPassword.zip main; ls;

      - name: Deploy ForgotPassword Test
        run: cd forgot-password/; go test -v ./...
       
      - name: ForgotPassword gobuild deploy
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.OIDC_GITHUB_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: SessionRetrieveAndValidateAPIKey

      - name: Update lambda
        run: aws lambda update-function-code --function-name  forgotPassword --zip-file fileb://forgot-password/addForgotPassword.zip
