name: Production - Deploy ChangePassword

on:
  push:
    branches: [main]
  workflow_dispatch:
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      # Deploy ChangePassword
      - name: Deploy change-password
        run: cd change-password/; GOOS=linux CGO_ENABLED=0 go build cmd/main.go; zip addChangePassword.zip main; ls;

      - name: Deploy ChangePassword Test
        run: cd change-password/; go test -v ./...

      - name: Deploy ChangePassword gobuild deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: changePassword
          zip_file: change-password/addChangePassword.zip
