name: Production - Deploy UpdateUser

on:
  push:
    branches: [main]
  workflow_dispatch:
    

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      # Deploy UpdateUser
      - name: Deploy user/update
        run: cd user/update/; GOOS=linux CGO_ENABLED=0 go build cmd/main.go; zip addUpdateUser.zip main; ls;

      - name: Deploy UpdateUser Test
        run: cd user/update/; go test -v ./...
                     
      - name: UpdateUser gobuild deploy
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.OIDC_GITHUB_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: SessionRetrieveAndValidateAPIKey

      - name: Update lambda
        run: aws lambda update-function-code --function-name  updateUserAttributes --zip-file fileb://user/update/addUpdateUser.zip
