name: Production - Deploy ConfirmSignupStateFunction

on:
  push:
    branches: [main]
  workflow_dispatch:
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      # Deploy ConfirmSignupStateFunction
      - name: Deploy confirm-signup-state-function
        run: cd confirm-signup-state-function/; GOOS=linux CGO_ENABLED=0 go build cmd/main.go; zip confirmSignupStateFunction.zip main; ls;

      - name: Deploy ConfirmSignupStateFunction Test
        run: cd confirm-signup-state-function/; go test -v ./...

      - name: Deploy ConfirmSignupStateFunction gobuild deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: confirmSignupStateFunction
          zip_file: confirm-signup-state-function/confirmSignupStateFunction.zip
