name: Production - Deploy ChangePassword

on:
  push:
    branches: [main]
  workflow_dispatch:
    

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      # Deploy ChangePassword
      - name: Deploy change-password
        run: cd change-password/; GOOS=linux CGO_ENABLED=0 go build cmd/main.go; zip addChangePassword.zip main; ls;

      - name: Deploy ChangePassword Test
        run: cd change-password/; go test -v ./...
         
      - name: ChangePassword gobuild deploy
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.OIDC_GITHUB_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: SessionRetrieveAndValidateAPIKey

      - name: Update lambda
        run: aws lambda update-function-code --function-name  changePassword --zip-file fileb://change-password/addChangePassword.zip
  
